spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:7777/realms/spring-boot-microservices

  zipkin:
    base-url: zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:password}@eureka:8761/eureka