server:
  port: 8081

spring:
  application:
    name: gateway
  cache:
    type: caffeine

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7777/realms/spring-boot-microservices

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:password}@localhost:8761/eureka

  instance:
    prefer-ip-address: true

